import = ["~/.config/alacritty/alacritty.local.toml"]

[font]
size = 11

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
x = 0
y = 0
