[[language]]
name = "cpp"
auto-format = true
formatter = { command = 'clang-format', args = ['--style=file'] }

[[language]]
name = "bash"
file-types = [
  "sh",
  "bash",
  "ash",
  "dash",
  "ksh",
  "mksh",
  "zsh",
  "zshenv",
  "zlogin",
  "zlogout",
  "zprofile",
  "zshrc",
  "eclass",
  "ebuild",
  "bazelrc",
  "Renviron",
  "zsh-theme",
  "cshrc",
  "tcshrc",
  "bashrc_Apple_Terminal",
  "zshrc_Apple_Terminal",
  { glob = "i3/config" },
  { glob = "sway/config" },
  { glob = "tmux.conf" },
  { glob = ".bash_history" },
  { glob = ".bash_login" },
  { glob = ".bash_logout" },
  { glob = ".bash_profile" },
  { glob = ".bashrc" },
  { glob = ".profile" },
  { glob = ".zshenv" },
  { glob = ".zlogin" },
  { glob = ".zlogout" },
  { glob = ".zprofile" },
  { glob = ".zshrc" },
  { glob = ".zimrc" },
  { glob = "APKBUILD" },
  { glob = ".bash_aliases" },
  { glob = ".Renviron" },
  { glob = ".xprofile" },
  { glob = ".xsession" },
  { glob = ".xsessionrc" },
  { glob = ".yashrc" },
  { glob = ".yash_profile" },
  { glob = ".hushlogin" },
  { glob = "*.build" },
  { glob = "*.buildfile" },
  { glob = "buildfile" },
  { glob = "testscript" },
  { glob = "*.testscript" },
]

[[language]]
name = "cpp"
file-types = ["cc",
              "hh",
              "c++",
              "cpp",
              "hpp",
              "h",
              "ipp",
              "tpp",
              "cxx",
              "hxx",
              "ixx",
              "txx",
              "ino",
              "C",
              "H",
              "cu",
              "cuh",
              "cppm",
              "h++",
              "ii",
              "inl",
              { glob = "*.h.in" },
              { glob = "*.hxx.in" },
              { glob = "*.hpp.in" },
              { glob = "*.h.in" },
             ]

[[language]]
name = "yaml"
file-types = ["yml",
              "yaml",
              { glob = ".prettierrc" },
              { glob = ".clangd" },
              { glob = ".clang-format" },
              { glob = ".clang-tidy" },
              { glob = "manifest" },
              { glob = "*.manifest" },
             ]
