shell:
  program: fish

font:
  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  AppleFontSmoothing: true
