[terminal.shell]
program = ".config\\shortcuts\\msys2_shell.cmd"
args = [
  "-ucrt64",
  "-defterm",
  "-here",
  "-no-start",
  "-use-full-path",
  "-shell",
  "zsh --login -c 'source ~/.vsdevenv.sh; zsh'"
]
