[terminal.shell]
program = "cmd.exe"
args = [
  "/c",
  """\
"cd %USERPROFILE% && \
  .config\\shortcuts\\msys2_shell.cmd \
    -ucrt64 \
    -defterm \
    -here \
    -no-start \
    -use-full-path \
    -shell \
    zsh --login"
  """
]
